apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./namespace.yaml
  - ./pod.yaml
generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
