apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod
  name: test-pod
  namespace: each-resource
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  containers:
  - image: nginx
    name: test-pod
    ports:
    - containerPort: 80
