apiVersion: v1
kind: Service
metadata:
  name: b-app
  namespace: transfer
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: b-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-app
  namespace: transfer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: b-app
  template:
    metadata:
      labels:
        app: b-app
    spec:
      containers:
        - name: web
          image: tutum/hello-world
          ports:
            - containerPort: 80
