apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rara-tan/argocd-orphan.git
    targetRevision: HEAD
    path: test
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
